// <auto-generated />
namespace SisprodIT2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TabelasChamados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelasChamados));
        
        string IMigrationMetadata.Id
        {
            get { return "201612020233508_TabelasChamados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
