// <auto-generated />
namespace SisprodIT2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovidoFinalizacaoRequerido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovidoFinalizacaoRequerido));
        
        string IMigrationMetadata.Id
        {
            get { return "201612041712334_RemovidoFinalizacaoRequerido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
